trigger:
  branches:
   include:
     - main
     - features/*

variables:
  path: '$(System.DefaultWorkingDirectory)/Count with List'
  

jobs:
- job: terraform_install_and_init_and_fmt
  displayName: Build 
  pool: pool-agent
  steps:
  - task: TerraformInstaller@1
    displayName: Terraform Install
    inputs:
      terraformVersion: 'latest'
  - task: TerraformTask@5
    inputs:
      provider: 'azurerm'
      command: 'init'
      workingDirectory: $(path)
      backendServiceArm: 'new-todo-yaml-pipeline-latest'
      backendAzureRmStorageAccountName: 'storagesliku22082025'
      backendAzureRmContainerName: 'tfstate'
      backendAzureRmKey: 'terraform.tfstate'
   