trigger:
  branches:
   include:
     - main
     - features/*

variables:
  

jobs:
- job: terraform install and init and fmt
  displayName: Build 
  pool: pool-agent
  steps:
  - task: TerraformInstaller@1
    displayName: Terraform Install
    inputs:
      terraformVersion: 'latest'
  
  - task: TerraformTask@5
    displayName: Terraform Init
    inputs:
      provider: 'azurerm'
      command: 'init'
      backendServiceArm: 'new-todo-yaml-pipeline-latest'
      backendAzureRmStorageAccountName: 'storagesliku22082025'
      backendAzureRmContainerName: 'tfstate'
      backendAzureRmKey: 'terraform.tfstate'
   